IF
Global("BFPatronsSpawn","GLOBAL",0)
THEN
RESPONSE #100
CreateCreature("BFILLI",[538.424],NE)
CreateCreature("BFSPID",[313.346],W)
CreateCreature("BFKOB",[223.366],N)
CreateCreature("BFFASH",[539.629],W)
CreateCreature("BFWOLF",[813.358],S)
CreateCreature("BFVAMP",[436.158],SE)
CreateCreature("BFGAXE",[935.550],W)
CreateCreature("BFGARC",[1026.488],S)
SetGlobal("BFPatronsSpawn","GLOBAL",1)
Continue()
END
